import "../styles/globals.css";
import "../styles/main.css";
import LayoutProvider from "@/components/providers/LayoutProvider";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import FontsProvider from "@/components/providers/FontsProvider";
import { poppins, roboto } from "@/libs/configs/config.styles";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Latest Resume Creator",
  description: "Generated by @vivekcsein",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <FontsProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </FontsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
